name = input("Enter your full name: ")

length = len(name)
find = name.find(" ")
f2 = name.find("w")
f3 = name.find("o")
f4 = name.rfind("o")
f5 = name.find("x")
cap = name.capitalize()
upper = name.upper()
lower = name.lower()
result = name.isdigit()
r2 = name.isalpha()
r3 = name.isalnum()
r4 = name.count("o")
r5 = name.replace("oo", "u")
print(length, find, f2, f3, f4, f5, cap, upper, lower, result, r2, r3, r4, r5)
